services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - ./backend/base/db.sqlite3:/app/base/db.sqlite3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend-test:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: backend-test
      command: sh -c "python backend/manage.py migrate && python backend/manage.py test base.tests"
      volumes:
        - ./backend:/app
        - ./backend/base/db.sqlite3:/app/base/db.sqlite3

  frontend-test:
    image: node:18.17.1
    container_name: frontend-test
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run test -- --coverage"
    environment:
      - NODE_ENV=test
    depends_on:
      - frontend

volumes:
  db_data:
